var Places = require("./places.js");
var Q = require("q");
var fs = require('fs');
var path = require('path');


const streets = [
    "75001"];

var t =[
    "75002",
    "75003",
    "75004",
    "75005",
    "75006",
    "75007",
    "75008",
    "75009",
    "75010",
    "75011",
    "75012",
    "75013",
    "75014",
    "75015",
    "75016",
    "75017",
    "75018",
    "75019",
    "75020",
    "Abbeville la Riviere",
    "Ableiges",
    "Ablis",
    "Ablon sur Seine",
    "Acheres",
    "Acheres la Foret",
    "Adainville",
    "Aigremont",
    "Aincourt",
    "Alfortville",
    "Ambleville",
    "Amenucourt",
    "Andilly",
    "Andresy",
    "Angerville",
    "Angervilliers",
    "Annet sur Marne",
    "antony",
    "Arcueil",
    "Argenteuil",
    "Armentieres en Brie",
    "Arnouville les Gonesse",
    "Arnouville les Mantes",
    "Arpajon",
    "Arrancourt",
    "Arronville",
    "Arthies",
    "Asnieres sur Oise",
    "asnieres sur seine",
    "Athis Mons",
    "Attainville",
    "Aubergenville",
    "Aubervilliers",
    "Auffargis",
    "Auffreville Brasseuil",
    "Aulnay sous Bois",
    "Aulnay sur Mauldre",
    "Auteuil",
    "Authon la Plaine",
    "Auvernaux",
    "Auvers Saint Georges",
    "Auvers sur Oise",
    "Avernes",
    "Avon",
    "Avrainville",
    "Bagneaux sur Loing",
    "bagneux",
    "Bagnolet",
    "Baillet en France",
    "Bailly",
    "Bailly Romainvilliers",
    "Ballainvilliers",
    "Ballancourt sur Essonne",
    "Banthelu",
    "Barbizon",
    "Baulne",
    "Bazainville",
    "Bazemont",
    "Beauchamp",
    "Beaumont sur Oise",
    "Bellefontaine",
    "Belloy en France",
    "Bennecourt",
    "Bernes sur Oise",
    "Berville",
    "Bessancourt",
    "Bethemont la Foret",
    "Beynes",
    "Bezons",
    "Bievres",
    "Blandy",
    "Blaru",
    "Bobigny",
    "Boigneville",
    "bois colombes",
    "Bois d'Arcy",
    "Bois Herpin",
    "Bois le Roi",
    "Boisemont",
    "Boissise le Roi",
    "Boissy la Riviere",
    "Boissy l'Aillerie", "Boissy le Chatel",
    "Boissy le Cutte",
    "Boissy le Sec",
    "Boissy Saint Leger",
    "Boissy sous Saint Yon",
    "Bondoufle",
    "Bondy",
    "Bonnelles",
    "Bonneuil en France",
    "Bonneuil sur Marne",
    "Bonnieres sur Seine",
    "Bouafle",
    "Bouffemont",
    "Bougival",
    "Bouleurs",
    "Boullay les Troux",
    "boulogne billancourt",
    "Bouqueval",
    "Bouray sur Juine",
    "bourg la reine",
    "Bourron Marlotte",
    "Boussy Saint Antoine",
    "Boutervilliers",
    "Boutigny sur Essonne",
    "Bouville",
    "Bray et Lu",
    "Bray sur Seine",
    "Brean?on",
    "Bretigny sur Orge",
    "Breuil Bois Robert",
    "Breuillet",
    "Breux Jouy",
    "Breval",
    "Brie Comte Robert",
    "Brieres les Scelles",
    "Brignancourt",
    "Briis sous Forges",
    "Brou sur Chantereine",
    "Brouy",
    "Brueil en Vexin",
    "Brunoy",
    "Bruyeres le Chatel",
    "Bruyeres sur Oise",
    "Bry sur Marne",
    "Buc",
    "Buchelay",
    "Buhy",
    "Bullion",
    "Buno Bonnevaux",
    "Bures sur Yvette",
    "Bussy Saint Georges",
    "Butry sur Oise",
    "Cachan",
    "Cannes ecluse",
    "Carrieres sous Poissy",
    "Carrieres sur Seine",
    "Cergy",
    "Cernay la Ville",
    "Cerny",
    "Cesson",
    "Chailly en Biere",
    "Chailly en Brie",
    "Chalifert",
    "Chalo Saint Mars",
    "Chalou Moulineux",
    "Chamarande",
    "Chambourcy",
    "Chamigny",
    "Champagne sur Oise",
    "Champagne sur Seine",
    "Champcueil",
    "Champigny sur Marne",
    "Champlan",
    "Champmotteux",
    "Champs sur Marne",
    "Chanteloup en Brie",
    "Chanteloup les Vignes",
    "Chapet",
    "Charenton le Pont",
    "Charmont",
    "Charny",
    "Chars",
    "Chartrettes",
    "Chateau Landon",
    "Chateaufort",
    "Chatenay en France",
    "chatenay malabry",
    "Chatignonville",
    "chatillon",
    "Chatou",
    "Chauconin Neufmontiers",
    "Chauffour les etrechy",
    "Chaumes en Brie",
    "Chaumontel",
    "Chaussy",
    "Chauvry",
    "Chavenay",
    "chaville",
    "Chelles",
    "Chennevieres les Louvres",
    "Chennevieres sur Marne",
    "Chenoise",
    "Cheptainville",
    "Cherence",
    "Chessy",
    "Chevannes",
    "Chevilly Larue",
    "Chevreuse",
    "Chevry Cossigny",
    "Chilly Mazarin",
    "Choisel",
    "Choisy en Brie",
    "Choisy le Roi",
    "Clairefontaine en Yvelines",
    "clamart",
    "Claye Souilly",
    "Clery en Vexin",
    "clichy",
    "Clichy sous Bois",
    "Coignieres",
    "Collegien",
    "colombes",
    "Combs la Ville",
    "Commeny",
    "Conches sur Gondoire",
    "Conde Sainte Libiaire",
    "Conde sur Vesgre",
    "Condecourt",
    "Conflans Sainte Honorine",
    "Congerville Thionville",
    "Congis sur Therouanne",
    "Corbeil Essonnes",
    "Corbreuse",
    "Cormeilles en Parisis",
    "Cormeilles en Vexin",
    "Coubert",
    "Coubron",
    "Couilly Pont aux Dames",
    "Coulommiers",
    "Coupvray",
    "Courances",
    "courbevoie",
    "Courcelles sur Viosne",
    "Courcouronnes",
    "Courdimanche",
    "Courdimanche sur Essonne",
    "Courpalay",
    "Courson Monteloup",
    "Courtry",
    "Crecy la Chapelle",
    "Cregy les Meaux",
    "Crespieres",
    "Creteil",
    "Croissy Beaubourg",
    "Croissy sur Seine",
    "Crosne",
    "Crouy sur Ourcq",
    "Dammarie les Lys",
    "Dammartin en Goele",
    "Dammartin en Serve",
    "Dampierre en Yvelines",
    "Dampmart",
    "Dannemois",
    "Deuil la Barre",
    "D'Huison Longueville", "Domont",
    "Donnemarie Dontilly",
    "Doue",
    "Dourdan",
    "Drancy",
    "Draveil",
    "Dugny",
    "Eaubonne",
    "echarcon",
    "ecouen",
    "Ecquevilly",
    "ecuelles",
    "egly",
    "egreville",
    "elancourt",
    "emance",
    "emerainville",
    "Enghien les Bains",
    "Ennery",
    "epiais les Louvres",
    "epiais Rhus",
    "epinay Champlatreux",
    "epinay sous Senart",
    "epinay sur Orge",
    "epinay sur Seine",
    "epone",
    "eragny",
    "Ermont",
    "Esbly",
    "Estouches",
    "etampes",
    "etiolles",
    "etrechy",
    "evecquemont",
    "evry",
    "evry Gregy sur Yerre",
    "ezanville",
    "Faremoutiers",
    "Ferolles Attilly",
    "Ferrieres en Brie",
    "Feucherolles",
    "Fleury Merogis",
    "Flexanville",
    "Flins sur Seine",
    "Follainville Dennemont",
    "Fontaine la Riviere",
    "Fontainebleau",
    "fontenay aux roses",
    "Fontenay en Parisis",
    "Fontenay le Fleury",
    "Fontenay le Vicomte",
    "Fontenay les Briis",
    "Fontenay Saint P?re",
    "Fontenay sous Bois",
    "Fontenay Tresigny",
    "Forges les Bains",
    "Fosses",
    "Fourqueux",
    "Franconville",
    "Fremainville",
    "Fremecourt",
    "Freneuse",
    "Frepillon",
    "Fresnes",
    "Frouville",
    "Gadancourt",
    "Gagny",
    "Gaillon sur Montcient",
    "Galluis",
    "Gambais",
    "Garancieres",
    "garches",
    "Gargenville",
    "Garges les Gonesse",
    "Gazeran",
    "Genainville",
    "Genicourt",
    "gennevilliers",
    "Gentilly",
    "Germigny l'eveque", "Gif sur Yvette",
    "Gironville sur Essonne",
    "Gometz la Ville",
    "Gometz le Chatel",
    "Gommecourt",
    "Gonesse",
    "Gouaix",
    "Gournay sur Marne",
    "Goussainville",
    "Goussonville",
    "Gouzangrez",
    "Gretz Armainvilliers",
    "Grez sur Loing",
    "Grigny",
    "Grisy les Platres",
    "Grisy Suisnes",
    "Groslay",
    "Grosrouvre",
    "Guerard",
    "Guermantes",
    "Guernes",
    "Guerville",
    "Guibeville",
    "Guignes",
    "Guigneville sur Essonne",
    "Guillerval",
    "Guiry en Vexin",
    "Guitrancourt",
    "Guyancourt",
    "Haravilliers",
    "Hardricourt",
    "Haute Isle",
    "Hedouville",
    "Herblay",
    "Hericy",
    "Hermeray",
    "Herouville",
    "Hodent",
    "Houdan",
    "Houilles",
    "Igny",
    "Issou",
    "issy les moulineaux",
    "Itteville",
    "Ivry sur Seine",
    "Jagny sous Bois",
    "Jambville",
    "Janville sur Juine",
    "Janvry",
    "Joinville le Pont",
    "Jouarre",
    "Jouars Pontchartrain",
    "Jouy en Josas",
    "Jouy le Chatel",
    "Jouy le Moutier",
    "Jouy sur Morin",
    "Juilly",
    "Jumeauville",
    "Juvisy sur Orge",
    "Juziers",
    "La Boissiere ecole",
    "La Celle les Bordes",
    "La Celle Saint Cloud",
    "La Celle sur Morin",
    "La Chapelle en Vexin",
    "La Chapelle Gauthier",
    "La Chapelle la Reine",
    "La Courneuve",
    "La Falaise",
    "La Ferte Alais",
    "La Ferte Gaucher",
    "La Ferte sous Jouarre",
    "La Foret le Roi",
    "La Foret Sainte Croix",
    "La Frette sur Seine",
    "la garenne colombes",
    "La Grande Paroisse",
    "La Houssaye en Brie",
    "La Norville",
    "La Queue en Brie",
    "La Queue les Yvelines",
    "La Roche Guyon",
    "La Rochette",
    "La Verriere",
    "La Ville du Bois",
    "La Villeneuve en Chevrie",
    "Labbeville",
    "Lagny sur Marne",
    "Lainville en Vexin",
    "Lardy",
    "Lassy",
    "Le Bellay en Vexin",
    "Le Blanc Mesnil",
    "Le Bourget",
    "Le Chatelet en Brie",
    "Le Chesnay",
    "Le Coudray Montceaux",
    "Le Heaulme",
    "Le Kremlin Bicetre",
    "Le Mee sur Seine",
    "Le Mesnil Aubry",
    "Le Mesnil le Roi",
    "Le Mesnil Saint Denis",
    "Le Pecq",
    "Le Perchay",
    "Le Perray en Yvelines",
    "Le Perreux sur Marne",
    "Le Pin",
    "Le Plessis Bouchard",
    "Le Plessis Gassot",
    "Le Plessis Luzarches",
    "Le Plessis Pate",
    "le plessis robinson",
    "Le Plessis Trevise",
    "Le Port Marly",
    "Le Pre Saint Gervais",
    "Le Raincy",
    "Le Thillay",
    "Le Tremblay sur Mauldre",
    "Le Val Saint Germain",
    "Le Vesinet",
    "Les Alluets le Roi",
    "Les Breviaires",
    "Les Clayes sous Bois",
    "Les Essarts le Roi",
    "Les Granges le Roi",
    "Les Lilas",
    "Les Loges en Josas",
    "Les Mesnuls",
    "Les Molieres",
    "Les Mureaux",
    "Les Pavillons sous Bois",
    "Les Ulis",
    "Lesigny",
    "L'etang la Ville", "Leudeville",
    "Leuville sur Orge",
    "levallois perret",
    "Levis Saint Nom",
    "L'Hay les Roses", "Lieusaint",
    "L'ile Saint Denis", "Limay",
    "Limeil Brevannes",
    "Limetz Villez",
    "Limours",
    "Linas",
    "L'Isle Adam", "Lisses",
    "Liverdy en Brie",
    "Livilliers",
    "Livry Gargan",
    "Livry sur Seine",
    "Lizy sur Ourcq",
    "Lognes",
    "Lommoye",
    "Longjumeau",
    "Longnes",
    "Longperrier",
    "Longpont sur Orge",
    "Longuesse",
    "Longueville",
    "Lorrez le Bocage Preaux",
    "Louveciennes",
    "Louvres",
    "Lumigny Nesles Ormeaux",
    "Luzarches",
    "Maffliers",
    "Magnanville",
    "Magny en Vexin",
    "Magny le Hongre",
    "Magny les Hameaux",
    "Maincy",
    "Maisons Alfort",
    "Maisons Laffitte",
    "Maisse",
    "malakoff",
    "Mandres les Roses",
    "Mantes la Jolie",
    "Mantes la Ville",
    "Marcoussis",
    "Marcq",
    "Mareil en France",
    "Mareil Marly",
    "Mareil sur Mauldre",
    "Mareuil les Meaux",
    "Margency",
    "Marines",
    "Marles en Brie",
    "Marly la Ville",
    "Marly le Roi",
    "marnes la coquette",
    "Marolles en Beauce",
    "Marolles en Brie",
    "Marolles en Hurepoix",
    "Marolles sur Seine",
    "Mary sur Marne",
    "Massy",
    "Mauchamps",
    "Maudetour en Vexin",
    "Maule",
    "Maulette",
    "Maurecourt",
    "Maurepas",
    "Meaux",
    "Medan",
    "Melun",
    "Mennecy",
    "Menouville",
    "Menucourt",
    "Mere",
    "Mereville",
    "Meriel",
    "Merobert",
    "Mery sur Oise",
    "Mespuits",
    "meudon",
    "Meulan",
    "Mezieres sur Seine",
    "Mezy sur Seine",
    "Milly la Foret",
    "Mitry Mory",
    "Moigny sur ecole",
    "Moisenay",
    "Moisselles",
    "Moisson",
    "Moissy Cramayel",
    "Mondeville",
    "Monnerville",
    "Montcourt Fromonville",
    "Montereau Fault Yonne",
    "Montesson",
    "Montevrain",
    "Montfermeil",
    "Montfort l'Amaury", "Montgeron",
    "Montgeroult",
    "Monthyon",
    "Montigny le Bretonneux",
    "Montigny Lencoup",
    "Montigny les Cormeilles",
    "Montigny sur Loing",
    "Montlhery",
    "Montlignon",
    "Montmagny",
    "Montmorency",
    "Montreuil",
    "Montreuil sur Epte",
    "montrouge",
    "Montry",
    "Montsoult",
    "Morainvilliers",
    "Morangis",
    "Moret sur Loing",
    "Morigny Champigny",
    "Mormant",
    "Morsang sur Orge",
    "Morsang sur Seine",
    "Mortcerf",
    "Mouroux",
    "Mours",
    "Mousseaux sur Seine",
    "Moussy",
    "Moussy le Neuf",
    "Nainville les Roches",
    "Nandy",
    "Nangis",
    "nanterre",
    "Nanteuil les Meaux",
    "Neauphle le Ch?teau",
    "Neauphle le Vieux",
    "Neauphlette",
    "Nemours",
    "Nerville la Foret",
    "Nesles la Vallee",
    "Neuilly en Vexin",
    "Neuilly Plaisance",
    "Neuilly sur Marne",
    "neuilly sur seine",
    "Neuville sur Oise",
    "Nezel",
    "Nogent sur Marne",
    "Nointel",
    "Noiseau",
    "Noisiel",
    "Noisy le Grand",
    "Noisy le Roi",
    "Noisy le Sec",
    "Noisy sur ecole",
    "Noisy sur Oise",
    "Nozay",
    "Nucourt",
    "Oinville sur Montcient",
    "Oissery",
    "Ollainville",
    "Omerville",
    "Oncy sur ecole",
    "Orcemont",
    "Orgerus",
    "Orgeval",
    "Orly",
    "Ormesson sur Marne",
    "Ormoy",
    "Ormoy la Riviere",
    "Orphin",
    "Orsay",
    "Orveau",
    "Osny",
    "Othis",
    "Ozoir la Ferriere",
    "Ozouer le Voulgis",
    "Palaiseau",
    "Pantin",
    "Paray Vieille Poste",
    "paris",
    "Paris 1",
    "Paris 10",
    "Paris 10eme",
    "Paris 11",
    "Paris 11eme",
    "Paris 12",
    "Paris 12eme",
    "Paris 13",
    "Paris 13eme",
    "Paris 14",
    "Paris 14eme",
    "Paris 15",
    "Paris 15eme",
    "Paris 16",
    "Paris 16eme",
    "Paris 17",
    "Paris 17eme",
    "Paris 18",
    "Paris 18eme",
    "Paris 19",
    "Paris 19eme",
    "Paris 1er",
    "Paris 2",
    "Paris 20",
    "Paris 20eme",
    "Paris 2eme",
    "Paris 3",
    "Paris 3eme",
    "Paris 4",
    "Paris 4eme",
    "Paris 5",
    "Paris 5eme",
    "Paris 6",
    "Paris 6eme",
    "Paris 7",
    "Paris 7eme",
    "Paris 8",
    "Paris 8eme",
    "Paris 9",
    "Paris 9eme",
    "Parmain",
    "Pecqueuse",
    "Perdreauville",
    "Perigny",
    "Persan",
    "Perthes",
    "Pierrefitte sur Seine",
    "Pierrelaye",
    "Piscop",
    "Plaisir",
    "Plessis Saint Benoist",
    "Poigny la Foret",
    "Poissy",
    "Pommeuse",
    "Pomponne",
    "Pontault Combault",
    "Pontcarre",
    "Pontoise",
    "Porcheville",
    "Presles",
    "Presles en Brie",
    "Pringy",
    "Provins",
    "Prunay en Yvelines",
    "Prunay sur Essonne",
    "Puiselet le Marais",
    "Puiseux en France",
    "Puiseux Pontoise",
    "Pussay",
    "puteaux",
    "Quincy sous Senart",
    "Quincy Voisins",
    "Raizeux",
    "Rambouillet",
    "Rebais",
    "Richarville",
    "Richebourg",
    "Ris Orangis",
    "Rochefort en Yvelines",
    "Rocquencourt",
    "Roinville",
    "Roinvilliers",
    "Roissy en Brie",
    "Roissy en France",
    "Romainville",
    "Ronquerolles",
    "Rosny sous Bois",
    "Rosny sur Seine",
    "Rozay en Brie",
    "Rubelles",
    "rueil malmaison",
    "Rungis",
    "Saacy sur Marne",
    "Saclas",
    "Saclay",
    "Sagy",
    "Saint Arnoult en Yvelines",
    "Saint Aubin",
    "Saint Augustin",
    "Saint Brice sous Foret",
    "Saint Cheron",
    "Saint Clair sur Epte",
    "saint cloud",
    "Saint Cyr en Arthies",
    "Saint Cyr la Riviere",
    "Saint Cyr l'ecole", "Saint Cyr sous Dourdan",
    "Saint Cyr sur Morin",
    "Saint Denis",
    "Saint Escobille",
    "Saint Fargeau Ponthierry",
    "Saint Germain de la Grange",
    "Saint Germain en Laye",
    "Saint Germain Laval",
    "Saint Germain les Arpajon",
    "Saint Germain les Corbeil",
    "Saint Germain sur Morin",
    "Saint Gervais",
    "Saint Gratien",
    "Saint Hilaire",
    "Saint Hilarion",
    "Saint Jean de Beauregard",
    "Saint Jean les Deux Jumeaux",
    "Saint Leger en Yvelines",
    "Saint Leu la Foret",
    "Saint Mammes",
    "Saint Mande",
    "Saint Mard",
    "Saint Martin de Brethencourt",
    "Saint Martin du Tertre",
    "Saint Martin la Garenne",
    "Saint Maur des Fosses",
    "Saint Maurice",
    "Saint Maurice Montcouronne",
    "Saint Michel sur Orge",
    "Saint Nom la Breteche",
    "Saint Ouen",
    "Saint Ouen l'Aumone", "Saint Pathus",
    "Saint Pierre du Perray",
    "Saint Pierre les Nemours",
    "Saint Prix",
    "Saint Remy les Chevreuse",
    "Saint Remy l'Honore", "Saint Sauveur sur ecole",
    "Saint Soupplets",
    "Saint Sulpice de Favieres",
    "Saint Thibault des Vignes",
    "Saint Vrain",
    "Saint Witz",
    "Saint Yon",
    "Sainte Colombe",
    "Sainte Genevieve des Bois",
    "Sainte Mesme",
    "Saintry sur Seine",
    "Saints",
    "Samois sur Seine",
    "Samoreau",
    "Sannois",
    "Santeny",
    "Santeuil",
    "Sarcelles",
    "Sartrouville",
    "Saulx les Chartreux",
    "Saulx Marchais",
    "Savigny le Temple",
    "Savigny sur Orge",
    "sceaux",
    "Seine Port",
    "Septeuil",
    "Seraincourt",
    "Sermaise",
    "Serris",
    "Servon",
    "Seugy",
    "Sevran",
    "sevres",
    "Soignolles en Brie",
    "Soindres",
    "Soisy sous Montmorency",
    "Soisy sur ecole",
    "Soisy sur Seine",
    "Solers",
    "Sonchamp",
    "Souppes sur Loing",
    "Sourdun",
    "Souzy la Briche",
    "Stains",
    "Sucy en Brie",
    "suresnes",
    "Survilliers",
    "Tacoignieres",
    "Taverny",
    "Tessancourt sur Aubette",
    "Themericourt",
    "Theuville",
    "Thiais",
    "Thiverval Grignon",
    "Thoiry",
    "Thomery",
    "Thorigny sur Marne",
    "Tigery",
    "Torcy",
    "Torfou",
    "Tournan en Brie",
    "Toussus le Noble",
    "Trappes",
    "Tremblay en France",
    "Triel sur Seine",
    "Trilport",
    "Us",
    "Vaires sur Marne",
    "Valenton",
    "Vallangoujard",
    "Valmondois",
    "Valpuiseaux",
    "vanves",
    "Varennes Jarcy",
    "Varennes sur Seine",
    "Varreddes",
    "vaucresson",
    "Vaudherland",
    "Vaugrigneuse",
    "Vauhallan",
    "Vaujours",
    "Vaureal",
    "Vaux le Penil",
    "Vaux sur Seine",
    "Vayres sur Essonne",
    "Velizy Villacoublay",
    "Vemars",
    "Veneux les Sablons",
    "Verneuil l'etang",
    "Verneuil sur Seine",
    "Vernou la Celle sur Seine",
    "Vernouillet",
    "Verrieres le Buisson",
    "Versailles",
    "Vert",
    "Vert le Grand",
    "Vert le Petit",
    "Vert Saint Denis",
    "Vetheuil",
    "Viarmes",
    "Videlles",
    "Vieille eglise en Yvelines",
    "Vienne en Arthies",
    "Vigneux sur Seine",
    "Vigny",
    "Villabe",
    "Villaines sous Bois",
    "ville d'avray",
    "Villebon sur Yvette",
    "Villeconin",
    "Villecresnes",
    "Villejuif",
    "Villejust",
    "Villemoisson sur Orge",
    "Villemomble",
    "villeneuve la garenne",
    "Villeneuve le Comte",
    "Villeneuve le Roi",
    "Villeneuve Saint Georges",
    "Villeneuve sur Auvers",
    "Villeneuve sur Bellot",
    "Villennes sur Seine",
    "Villenoy",
    "Villeparisis",
    "Villepinte",
    "Villepreux",
    "Villeron",
    "Villers en Arthies",
    "Villetaneuse",
    "Villevaude",
    "Villiers Adam",
    "Villiers le Bacle",
    "Villiers le Bel",
    "Villiers le Mahieu",
    "Villiers le Sec",
    "Villiers Saint Frederic",
    "Villiers Saint Georges",
    "Villiers sur Marne",
    "Villiers sur Morin",
    "Villiers sur Orge",
    "Vincennes",
    "Viroflay",
    "Viry Chatillon",
    "Vitry sur Seine",
    "Voisins le Bretonneux",
    "Voulangis",
    "Voulx",
    "Vulaines sur Seine",
    "Wissous",
    "Wy dit Joli Village",
    "Yerres",

];

const roles = ["Plombier", "Serrurier", "Vitrier", "Electricien"];

function onError(err) {
    if (err) {
        return console.error(err);
    }

    console.log('unknown error');
}

function writeJsonToFile(filename, data) {
    var json = JSON.stringify(data);
    fs.writeFileSync(path.join("data", filename + '.json'), json);
}

var filenameCounter = 0;

roles.forEach(function (role) {
    streets.forEach(function (street) {
        var query = role + ' in ' + street;

        Places.getPlaces(query)
            .then(function (places) {
                console.log('got places', query);

                var promises = [];

                places.forEach(function (place) {
                    console.log('requesting place details', query);
                    promises.push(Places.getPlaceDetails(place.id));
                });

                Q.all(promises).then(function(placesDetails){

                    console.log('writing results to file', filenameCounter, query);

                    writeJsonToFile(filenameCounter, [{query: query, results: placesDetails}]);
                    filenameCounter++

                }, onError);

            }, onError);

    })
});

